/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )


extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern APTR                  VisualInfo;
extern struct Window        *PIPWnd;
extern struct Menu          *PIPMenus;
extern UWORD                 PIPLeft;
extern UWORD                 PIPTop;
extern UWORD                 PIPWidth;
extern UWORD                 PIPHeight;
extern UBYTE                *PIPWdt;
extern struct TextAttr       topaz8;
extern struct NewMenu        PIPNewMenu[];
extern struct ColorSpec      ScreenColors[];
extern UWORD                 DriPens[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int OpenPIPWindow( void );
extern void ClosePIPWindow( void );

extern UBYTE Ver[];
extern UWORD screenWidth, screenHeight;
