/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_SI_ANNO                             0
#define GD_SI_NAME                             1
#define GD_SI_AUTH                             2
#define GD_SI_COPY                             3
#define GD_SI_SAVE                             4
#define GD_SI_CANCEL                           5

#define GDX_SI_ANNO                            0
#define GDX_SI_NAME                            1
#define GDX_SI_AUTH                            2
#define GDX_SI_COPY                            3
#define GDX_SI_SAVE                            4
#define GDX_SI_CANCEL                          5

#define SampleInfo_CNT 6

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *SampleInfoWnd;
extern struct Gadget        *SampleInfoGList;
extern struct Gadget        *SampleInfoGadgets[6];
extern UWORD                 SampleInfoLeft;
extern UWORD                 SampleInfoTop;
extern UWORD                 SampleInfoWidth;
extern UWORD                 SampleInfoHeight;
extern UBYTE                *SampleInfoWdt;
extern struct TextAttr       topaz8;
extern UWORD                 SampleInfoGTypes[];
extern struct NewGadget      SampleInfoNGad[];
extern ULONG                 SampleInfoGTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int OpenSampleInfoWindow( void );
extern void CloseSampleInfoWindow( void );
